language: php

services:
  - mysql

env:
  global:
    - WP_DB_USER=wp
    - WP_DB_PASS=password
    - WP_DB_NAME=wp_tests
    - WP_VERSION=*

php:
  - 7.4
  - 7.3
  - 7.2
  - 5.6

matrix:
  include:
    - php: 5.
      env: WP_VERSION=4.4.0

before_script:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
  - mysql -u root -e "CREATE DATABASE ${WP_DB_NAME};"

install:
  - composer validate --no-check-lock --strict composer.json
  - composer require --no-update --dev roots/wordpress:${WP_VERSION} wp-phpunit/wp-phpunit:${WP_VERSION}
  - composer install
  - composer show

script:
  - ./vendor/bin/phpunit tests --testdox